# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3675b98dafdd890126dc05334baf91ec6ac3cb6b8d5d33b81370650a2b634356e610a7b833bf4678d6fc0bd4c0dcb5a4bbff925f7bbebf9b19040200c12d734
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>

test:
  secret_key_base: f97f12f76f1fde6e7d6ca26d66972bc29c1a01a066fbed024160d195dea3204ae456c0f99f33eb74ded7b3b718e1ae07e2992b7fe8f2ad6833ec9501a11ae2ed
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
